spring:
  datasource:
    url: jdbc:mysql://localhost/springtransaction?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
user:
  timezone: UTC

logging:
  level: debug
